// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as WelcomeText$RescriptHello from "../components/WelcomeText.bs.js";

function App(Props) {
  return React.createElement("div", undefined, React.createElement(WelcomeText$RescriptHello.make, {}));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
