// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function WelcomeText(Props) {
  return React.createElement("h1", {
              className: "white-text"
            }, "Hello World!");
}

var make = WelcomeText;

export {
  make ,
  
}
/* react Not a pure module */
