// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as App$RescriptHello from "./views/App.bs.js";

var root = document.querySelector("#root");

if (root == null) {
  console.log("Error: could not find react element");
} else {
  ReactDom.render(React.createElement(App$RescriptHello.make, {}), root);
}

export {
  
}
/* root Not a pure module */
